<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>logout</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>f5ecf911-2ab4-4381-b576-17fa5b876e3f</testSuiteGuid>
   <testCaseLink>
      <guid>65b9f823-7563-4771-8bad-3873ff3f65ad</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login dan Logout/Logout</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>cf85827c-ec33-4764-8d69-2b0ea5273a22</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/data_binding_logout</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>cf85827c-ec33-4764-8d69-2b0ea5273a22</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>expected_logout</value>
         <variableId>d1426998-4ac8-4616-8a0a-b97a5f2754b4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>cf85827c-ec33-4764-8d69-2b0ea5273a22</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>status_logout</value>
         <variableId>777662b1-a5e9-467d-b308-701b01c585b1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c17ec9a3-2d6b-45a4-bc4d-c712e5bf453e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6ec70425-5e6c-43ab-9c17-3e4b73df00f5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fb390871-90dc-4c63-a481-2045394dcef0</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
